## See: https://sw.kovidgoyal.net/kitty/conf/#kitty-conf 
## for all configuration options as well as a sample kitty.conf file

shell /opt/homebrew/bin/fish
shell_integration no-rc

startup_session default.kitty-session

font_family      JetBrains Mono
italic_font      auto
bold_font        auto
bold_italic_font auto

font_size        16.0
disable_ligatures never

background_opacity 1
background_blur 15

cursor_shape     beam

open_url_modifiers ctrl
open_url_with default

term xterm-kitty

window_margin_width 15
hide_window_decorations no
macos_option_as_alt yes
macos_quit_when_last_window_closed yes
macos_hide_from_tasks no

macos_titlebar_color default

## Keybinds
## You can use the special action no_op to unmap a keyboard shortcut that is
## assigned in the default configuration.

kitty_mod ctrl+shift

map kitty_mod+c         copy_to_clipboard
map kitty_mod+v         paste_from_clipboard
map kitty_mod+up        scroll_line_up
map kitty_mod+k         scroll_line_up
map kitty_mod+down      scroll_line_down
map kitty_mod+j         scroll_line_down
map kitty_mod+right     next_tab
map kitty_mod+left      previous_tab
map kitty_mod+t         new_tab
map kitty_mod+q         close_tab
map kitty_mod+.         move_tab_forward
map kitty_mod+,         move_tab_backward
map kitty_mod+up        increase_font_size
map kitty_mod+down      decrease_font_size
map kitty_mod+backspace restore_font_size

## Set color scheme
include ./themes/catppuccin-mocha.conf
